services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
    command: "sleep infinity"
    working_dir: /workspace